#!/usr/bin/env node

const { environnement } = require('./config.json');
const shell = Object.keys(environnement)
    .filter(key => typeof environnement[key] !== 'object')
    .map(key => `export ${key}=${JSON.stringify(environnement[key])}`)
    .join('\n');

process.stdout.write(shell);

