#!/usr/bin/env node

const config = require('./config.json');

const shell = Object.keys(config)
    .filter(key => typeof config[key] !== 'object')
    .map(key => `export ${key}=${JSON.stringify(config[key])}`)
    .join('\n');

process.stdout.write(shell);

