#!/bin/sh

# gitget  https://github.com/Inist-CNRS/lodex-extended public/resources /tmp/truc

REPOSITORY=${1:?the first argument of the command should be the URL of a git repository.}
BRANCH=${2:-master}
SOURCE=$3
TARGET=${4:-/app/public}

LOCATION=$(dirname $TARGET)
DIRECTORY=$(basename $TARGET)

WORKDIR=/tmp/gitsyncdir

echo "Syncing $WORKDIR from $REPOSITORY with $BRANCH"

(test ! -d "$WORKDIR/" && mkdir -p "$WORKDIR/")
test -d "$WORKDIR/.git" &&  rm -rf "$WORKDIR/.git"
cd "$WORKDIR/"
git init
git remote add origin "$REPOSITORY"

git config core.sparseCheckout true
echo $SOURCE >> .git/info/sparse-checkout

git -c core.askpass=true fetch --all
git reset --hard "origin/$BRANCH"
rm -rf "$WORKDIR/.git"

(test -d "$TARGET/" && rm -rf "$TARGET/" )

mkdir -p $TARGET
mv $WORKDIR/$SOURCE/* $TARGET/
