#!/bin/bash


DIRECTORY=www
LOCATION=$(cd `dirname $0` && pwd)
REPOSITORY=${1:?the first argument of the command should be the URL of a git repository.}
BRANCH=${2:-master}

echo "Syncing $LOCATION/$DIRECTORY from $REPOSITORY with branch $BRANCH"

test ! -d "$LOCATION/$DIRECTORY/" && mkdir -p "$LOCATION/$DIRECTORY/"
test -d "$LOCATION/$DIRECTORY/.git" &&  rm -rf "$LOCATION/$DIRECTORY/.git"
cd "$LOCATION/$DIRECTORY/" && git init && git remote add origin "$REPOSITORY"
cd "$LOCATION/$DIRECTORY/" && git -c core.askpass=true fetch --all && git reset --hard "origin/$BRANCH"
cd "$LOCATION/$DIRECTORY/" && (git -c core.askpass=true ls-remote -q $REPOSITORY >/dev/null || rm -rf "$LOCATION/$DIRECTORY/.git")

