#!/usr/bin/env node

const { packages } = require('./config.json');
const npm = require('npm-programmatic');

npm.install(packages || [], { output: true })
    .then(() => console.log("All packages installed."))
    .catch((e) => console.error('Unable to install package', e));

